export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_MOBILE = 'SET_MOBILE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RECEIVE_PRODUCTS_LIST = 'RECEIVE_PRODUCTS_LIST';
export const RECEIVE_PRODUCT_BEGIN = 'RECEIVE_PRODUCT_BEGIN';
export const RECEIVE_PRODUCT_COMPLETED = 'RECEIVE_PRODUCT_COMPLETED';
export const RECEIVE_CATEGORIES_LIST = 'RECEIVE_CATEGORIES_LIST';
export const RECEIVE_CATEGORY_BEGIN = 'RECEIVE_CATEGORY_BEGIN';
export const RECEIVE_CATEGORY_COMPLETED = 'RECEIVE_CATEGORY_COMPLETED';

export const RECEIVE_ORDERS_LIST = 'RECEIVE_ORDERS_LIST';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
